version: "3.1"

networks:
  flcrd.nw:

services:

  flcrd-test-db:
    container_name: flcrd-test-db
    image: flcrd-test-db:latest
    environment:
      POSTGRES_DB: flcrd
      POSTGRES_USER: flcrd
      POSTGRES_PASSWORD: flcrd
    volumes:
      - /tmp/flcrd-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      flcrd.nw:
        aliases:
          - flcrd-test-db

  flcrd-api:
    container_name: flcrd-api
    image: registry.gitlab.com/alvox-env/registry/flcrd-api:latest
    restart: unless-stopped
#    ports:
#      - 5000:5000
    environment:
      PORT: :5000
      DSN: postgres://flcrd:flcrd@flcrd-test-db/flcrd?sslmode=disable
      APPKEY: myappkey
    networks:
      flcrd.nw:
        aliases:
          - flcrd-api

  flcrd-nginx:
    container_name: flcrd-nginx
    image: nginx:1.17-alpine
    volumes:
      - /Users/al/a/flcrd-web/env/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/flcrd-proxy/nginx-cache:/var/cache/nginx
      - /tmp/flcrd-proxy/nginx-pid:/var/run
    ports:
      - 80:80
    networks:
      flcrd.nw:
        aliases:
          - flcrd-nginx