name: Build image
on:
  push:
    branches: 
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build binary
      run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app cmd/web/*
    
    - name: Build image
      run: docker build -t docker.pkg.github.com/alvox/flcrd-web/flcrd-api:latest .
    
    - name: Push image
      env:
        PKG_TOKEN: ${{ secrets.github_pkg_token }}
      run: |
        docker login docker.pkg.github.com --username alvox --password $PKG_TOKEN
        docker push docker.pkg.github.com/alvox/flcrd-web/flcrd-api:latest
    
